### ISSUE TITLE
Demo won't start in UE 5.4.4...  Installed from FAB not github..

### ISSUE THREAD

**Issue by yndarx** [chaintree7/EventDriven-AttributeSystem#1]
I added the .ini file in the TAGS folder as the instructions said.. 

Getting the following error when trying to play demo.
![image](https://github.com/user-attachments/assets/fe683e80-3e57-43b7-a7eb-b959a84c2f15)

Appreciate the work that went into this and providing it free regardless..

**Comment by yndarx** [comment]
the project works fine when downloading from here.. FYI

**Comment by chaintree7** [comment]
After add ini, you need to restart project

**Comment by yndarx** [comment]
I did restart the project.. same error my friend.

**Comment by chaintree7** [comment]
![image](https://github.com/user-attachments/assets/cbfbfc29-77d8-4248-bfe5-3fe8d5d270da)
path correct?

**Comment by yndarx** [comment]
yes.. Going to delete and add to new thirdperson project again for the 2nd time..  one moment while I do it again.

**Comment by yndarx** [comment]
it worked this time.. only difference is I added the .ini to the /config/Tags folder while the project was closed .. previously I added it while it was open and then restarted it..   in case somebody else has the same issue.
